version: '3.8'

services:
  bookstore-blazor:
    image: acme/bookstore-blazor:latest
    container_name: bookstore-blazor
    build:
      context: ../../
      dockerfile: src/Acme.BookStore.Blazor/Dockerfile.local
    ports:
      - "44307:80"
    depends_on:
      - bookstore-api
    restart: on-failure
    volumes:
      - ./appsettings.json:/usr/share/nginx/html/appsettings.json
    networks:
      - abp-network

  bookstore-api:
    image: acme/bookstore-api:latest
    container_name: bookstore-api
    hostname: bookstore-api
    build:
      context: ../../
      dockerfile: src/Acme.BookStore.HttpApi.Host/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=1a25a865-cf6d-4252-9df5-dad17144d7ad
      - App__SelfUrl=https://localhost:44354
      - App__CorsOrigins=http://localhost:44307
      - App__HealthCheckUrl=http://bookstore-api/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=https://localhost:44354
      - ConnectionStrings__Default=DataSource=/data/BookStore.db
    ports:
      - "44354:443"
    depends_on:
      sqlite:
        condition: service_healthy
    restart: on-failure    
    volumes:
      - sqlite_data:/data
      - ./certs:/root/certificate
    networks:
      - abp-network
  


  db-migrator:
    image: acme/bookstore-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/BookStore.DbMigrator/Dockerfile.local
    environment:
      - OpenIddict__Applications__BookStore_Blazor__RootUrl=http://localhost:44307
      - ConnectionStrings__Default=DataSource=/data/BookStore.db
      - Redis__Configuration=redis
    restart: on-failure
    volumes:
      - sqlite_data:/data
    depends_on:
      sqlite:
        condition: service_healthy
    networks:
      - abp-network    
  
  sqlite:
    container_name: sqlite-container
    image: alpine:latest    
    command: sh -c "apk add sqlite && touch /data/BookStore.db && sqlite3 /data/BookStore.db '.databases' && tail -f /dev/null"
    environment:
      - TZ=UTC
    volumes:
      - sqlite_data:/data
    networks:
      - abp-network
    healthcheck:
      test: ["CMD-SHELL", "if [ -f /data/BookStore.db ]; then exit 0; else exit 1; fi"]
      interval: 10s
      timeout: 3s
      retries: 10  
volumes:
  sqlite_data:
    name: bookstore_sqlite_data
networks:
  abp-network:
    name: bookstore-network
    driver: bridge